%% load the nanodot system parameters
clc; clearvars;
load("nanodot_sys.mat")

% run control using electric fields
mu = muE;

% determine starting/target states/occupancies
ni = 4;
nf = 7;
psi_i = states(:,ni);
psi_f = states(:,nf);

% get transition diagnostics
[muRot,rotT] = rotate_dipoles(psi_i,psi_f,mu);
QSL = get_QSL("levi",states,H,M);
TDM = vecnorm(get_TDM(states,mu),2,3);

% determine the timestep/span values
numQSL = 40;		% multiply by the QSL to obtain the total time
tMult = 10 * fs;	% ensure total duration is a multiple of tMult

T = ceil(numQSL * QSL(ni,nf)/tMult)*tMult;
numTau = 200 * numQSL;
tgrid = linspace(0,T,numTau+1);

fprintf("T = %i fs \n",round(T/fs));
clearvars numQSL tMult

%% get the quantum control result
%-----------------------------------------------------------
env = pulse_envelope(tgrid,"sine",[T/6,T/6]);
field = zeros(numel(mu),numTau+1);

% use a small initial step
QC_opts = { ...
	"linesearch",	1, ...
	"learnrate",	0.05, ...
	"maxIters",		1, ...
	"cutoff",		0.95, ...
	"plotting",		true, ...
	"propagator",	"CN", ...
	"propOpts",		{"method","cgs"}, ...
	"envelope",		env, ...
	"stallTol",		0, ...
	};
[~,~,~,field] = optimize_field(psi_i,psi_f',tgrid,field,H,mu,M,QC_opts{:});

% run remaining iterations using initial field
QC_opts = { ...
	"linesearch",	1, ...
	"learnrate",	0.75, ...
	"maxIters",		60, ...
	"cutoff",		0.975, ...
	"plotting",		true, ...
	"propagator",	"CN", ...
	"propOpts",		{"method","cgs"}, ...
	"envelope",		env, ...
	"stallTol",		0, ...
	"savefile",		"nanodot_4_7_QC_prog.mat", ...
	};

[P,Pt,dP,field,psiFwd,exitFlag] = optimize_field(psi_i,psi_f',tgrid,field,H,mu,M,QC_opts{:});

% save
save("nanodot_4_7_QC.mat")